---
title: "Summary of models included in rtedem"
author: "K Todd-Brown (ktoddbrown@gmail.com)"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

There are several soil decomposition models already coded into *rtedem* including: CENTURY, TECO, CLM, and YASSO07.

```{r}
library(ggplot2)
library(reshape2)
library(plyr)
library(Matrix)
library(rtedem)
#library(assertthat)
#source('../R/dC.biomassModel.R')

codedParameters <- publishedParameters()

minMaxBounds <- makeModelBounds(codedParameters)
```


```{r plotTurnover, fig.width=6}

turnovers <- ldply(names(minMaxBounds), function(xx){
  ans <- minMaxBounds[[xx]][grepl('K', minMaxBounds[[xx]]$name),]
  ans[,c('true', 'min', 'max')] <- ans[,c('true', 'min', 'max')] * -1
  ans$model <- xx
  return(ans)
})
turnovers$modelIndex <- as.numeric(as.factor(turnovers$model))
yAxis <- unique(turnovers[,c('model', 'modelIndex')])
ggplot(turnovers) + geom_rect(aes(ymax=modelIndex+0.45, ymin=modelIndex-0.45, xmax=min/365, xmin=max/365, fill=name)) + 
  geom_point(aes(y=modelIndex, x=true/365)) + 
  scale_x_log10() + scale_y_continuous(breaks=yAxis$modelIndex, labels=yAxis$model) +
  labs(title='Comparison of turnover times', y='', x='time [yr]') + guides(fill=FALSE)
```

```{r}
decayMatrix <- llply(codedParameters, function(xx){
  Turnover <- Matrix(diag(xx$tau/365))
  A <- matrix(data=0, nrow=dim(Turnover)[1], ncol=dim(Turnover)[2])
  A[as.numeric(gsub('A', '', xx$trans$name))] <- xx$trans$val
  return(list(turnover = Turnover, transfer=Matrix(A), K=Matrix(diag(1/(xx$tau/365)))))
})

l_ply(names(codedParameters), function(xx){
  #cat(xx,' turnover [year]:\n');print(decayMatrix[[xx]]$turnover)
  cat(xx, ' transfer Matrix:\n');print(decayMatrix[[xx]]$transfer)
})

l_ply(names(codedParameters), function(xx){
  cat(xx, 'decay Matrix (1/tau*transfer):\n')
  A <- decayMatrix[[xx]]$transfer
  diag(A) <- -1
  print(decayMatrix[[xx]]$K %*% A)
})
```

```{r SCB}
par <- unlist(list('v_enz'=1, 'km_enz'=0.1,
                      'v_up'=1, 'km_up'=0.2,
                       'cue'=0.7, 'basal' = 0.01,
                       'turnover_b'=0.1,
                       a1=0.1, a2=0.8))
model <- runModel(par, timeArr= floor(2^(seq(0, 6, length=50))), cModel=dC.biomassModel, poolAssignment=list(simple=1, complex=2, biomass=3))
ggplot(melt(model, id.vars=c('time', 'label'))) + geom_line(aes(x=time, y=value,  color=variable)) + scale_x_log10()

synData <- createSynData(par=par, timeArr=floor(2^(seq(0, 6, length=50))), cModel=dC.biomassModel, poolAssignment=list(simple=1, complex=2, biomass=3))
ggplot(synData) + geom_point(aes(x=time, y=mean, color=variable)) + geom_errorbar(aes(x=time, ymin=mean-sd, ymax=mean+sd, color=variable)) + scale_x_log10()
```

```{r SCEB}
par <- unlist(list('v_enz'=1, 'km_enz'=0.1,
                  'v_up'=1, 'km_up'=0.2,
                  'enzProd'=0.01, 'enzCost'=0.75, 
                  'cue'=0.7, 'basal' = 0.01,'turnover_e'=0.1,
                  'turnover_b'=0.5, 
                  a1=0.1, a2=0.7, a3=0.05))
model <- runModel(par, timeArr= floor(2^(seq(0, 6, length=50))), cModel=dC.biomassModel, poolAssignment=list(simple=1, complex=2, enzyme=3, biomass=4))
ggplot(melt(model, id.vars=c('time', 'label'))) + geom_line(aes(x=time, y=value,  color=variable)) + scale_x_log10()

synData <- createSynData(par=par, timeArr=floor(2^(seq(0, 6, length=50))), cModel=dC.biomassModel, poolAssignment=list(simple=1, complex=2, enzyme=3, biomass=4))
ggplot(synData) + geom_point(aes(x=time, y=mean, color=variable)) + geom_errorbar(aes(x=time, ymin=mean-sd, ymax=mean+sd, color=variable)) + scale_x_log10()
```
